### ISSUE TITLE
Faraday issue

### ISSUE THREAD

**Issue by Nerian** [gocardless/gocardless-pro-ruby#50]
Hi,

Looks like there is some incompatibility with the latest version of faraday.

This works fine:
`gem 'faraday', '0.15.4'`

This gives me an error
`gem 'faraday', '0.16.2'`

I am using gocardless_pro-2.14.0.

```
NoMethodError:
       undefined method `each' for nil:NilClass

/Users/Nerian/.rvm/gems/ruby-2.6.3/gems/faraday-0.16.2/lib/faraday/options.rb:52:in `merge!'
     # /Users/Nerian/.rvm/gems/ruby-2.6.3/gems/faraday-0.16.2/lib/faraday/options.rb:67:in `merge'
     # /Users/Nerian/.rvm/gems/ruby-2.6.3/gems/faraday-0.16.2/lib/faraday.rb:83:in `new'
     # /Users/Nerian/.rvm/gems/ruby-2.6.3/gems/gocardless_pro-2.14.0/lib/gocardless_pro/api_service.rb:28:in `initialize'
     # /Users/Nerian/.rvm/gems/ruby-2.6.3/gems/gocardless_pro-2.14.0/lib/gocardless_pro/client.rb:106:in `new'
     # /Users/Nerian/.rvm/gems/ruby-2.6.3/gems/gocardless_pro-2.14.0/lib/gocardless_pro/client.rb:106:in `initialize'
```

The code that gives the error:
```
GoCardlessPro::Client.new(access_token: '.......' , environment: :sandbox)
```

**Comment by matt-thomson** [comment]
Hi @Nerian, are you able to try again with Faraday 0.17.0? The 0.16.x releases had more changes than the Faraday team were expecting, so they rolled them back: https://github.com/lostisland/faraday/releases/tag/v0.17.0
